version: "3.5"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qrodizio_development
    volumes:
      - qrodiziodb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    command: "flask run --host=0.0.0.0"
    build: .
    volumes:
      - .:/usr/src/backend/
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  qrodiziodb-data:
