[default]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
TITLE = "QRodizio"
SECRET_KEY = "this-is-super-secret!"

EXTENSIONS = [
    "qrodizio.blueprints.api:init_app",
]


[development]
#EXTENSIONS = [
#    "OTHER_EXTENSIONS_HERE",
#    "dynaconf_merge_unique"  # to reuse extensions list from [default]
#]
DEBUG = true

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'

#[production]
#SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'
